INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('ligo_science_goals', 'Science Goals of LIGO','Describe the science goals of LIGO.',3,'B',10,'SW');
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('wave_properties','Seismic Wave Properties.','Describe the basic properties of seismic waves.',3,'B',15,'SW');
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('seismic_data_importance','Why Seismic Data is Important.','Explain the need for LIGO to study seismic data.',3,'B',20,'SW');
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('seismometer_locations','Locations of Ligo Seismometers','Identify locations of LIGO seismometers.',3,'B',30,'SW');
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('practice_making_plots', 'Practice Plots of Seismic Data','Practice making plots of LIGO seismic data.',3,'B',40 ,'SW');
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('ligo_research_question','Our Research Question and Plan', 'Make a research question and plan.',3,'B',50,'SW' );
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('ligo_analysis','Notes on Analyzing the Data', 'Analyze data to answer your research question.',3,'C',20,'SW' );
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('ligo_test_answer', 'Notes on Testing our Answer','Test your answer.',3,'C',30,'SW');
INSERT INTO keyword (keyword,description,milestone,project_id,section,section_id,type) VALUES ('ligo_improve_answer', 'Notes on Improving our Answer','Improve your answer.',3,'C',40,'SW');
