<?php
//
//  Project News for I2U2
//  Last updated on Sat, 28 Feb 2009 02:54:50 GMT 
//
//  Note! You no longer need to edit this file by hand!
//  You can instead (if you wish) use http://www13.i2u2.org/ops/news_admin.php 
//

$project_news = array(
    array("title" => "Teacher Internships at LIGO Observatories",
        "description" => "LIGO will host two six-week long teacher internships this summer at each Observatory through the National Science Foundation's Research Experience for Teachers (RET) program. ",
        "date" => "February 28, 2009",
        "link" => "http://www.ligo-wa.caltech.edu/internships.html",
        "author" => "myers"
    ),

    array("title" => "Listening to the Stars - Feb 2009",
        "description" => "Read the latest news from the LIGO Hanford Observatory, including activities for the International Year of Astronomy 2009. ",
        "date" => "February 28, 2009",
        "link" => "http://www.i2u2.org/library/index.php/Listening_to_the_Stars/Feb2008",
        "author" => "Ingram"
    ),

    array("title" => "Fermilab Masterclass",
        "description" => "On Saturday 21 February, students and teachers from northern Illinois will gather at the Fermi National Accelerator Laboratory for a day of QuarkNet Masterclass, where they will learn about particle physics by working with physicists to analyze real data from CERN. ",
        "date" => "February 10, 2009",
        "link" => "http://www.quarknet.us/library/index.php/Masterclass_at_Fermilab",
        "author" => "myers"
    ),

    array("title" => "Listening to the Stars - Nov 2008",
        "description" => "Read the latest news from the LIGO Hanford Observatory, including the new &quot;Golf Ball Racer&quot; exhibit and the new Output Mode Cleaners.",
        "date" => "November 27, 2008",
        "link" => "http://www13.i2u2.org/library/index.php?title=Listening_to_the_Stars/Nov2008",
        "author" => "Dale Ingram"
    ),

    array("title" => "I2U2 is hiring",
        "description" => "&quot;Interactions in Understanding the Universe&quot; would like to hire a software developer.  
See the Bulletin Board for details. ",
        "date" => "September 30, 2008",
        "link" => "/forum_thread.php?id=216",
        "author" => "myers"
    ),

    array("title" => "Availability of LIGO data over the summer",
        "description" => "Due to work at the LIGO Hanford Observatory this summer, there may be occasions when new data are not being generated for the LIGO e-Lab.   
See the Bulletin Board for more details.",
        "date" => "June 13, 2008",
        "link" => "/forum_thread.php?id=164",
        "author" => "myers"
    ),

    array("title" => "LIGO data interuption",
        "description" => "Due to a framebuilder upgrade on Thursday minute trend and second trend PEM data are not being made available to I2U2.  This has been reported and a fix is in the works.  
Expect data to flow again later today, or soon after. 
<font color=green>Fixed.</font>",
        "date" => "June 6, 2008",
        "author" => "myers"
    ),

    array("title" => "Cosmic Ray e-Lab milesone",
        "description" => "On Tuesday, 29 April 2008 the Cosmic Rays e-Lab database crossed a significant milestone: 15,000 data files.  We have grown by 5,000 files in one year.  Thanks to those schools contributing uploads. Keep up the data flow.

",
        "date" => "2 May 2008",
        "author" => "rspete"
    ),

    array("title" => "QuarkNet Fellows Library",
        "description" => "The <a href='http://www13.i2u2.org/cosmic/library/'>QuarkNet Fellows Library</a> (wiki) has been set up for the Fellows to work on e-Lab development.",
        "date" => "October 22, 2007",
        "link" => "http://www13.i2u2.org/cosmic/library/",
        "author" => "rspete"
    ),

    array("title" => "Hanford off-line",
        "description" => "The Hanford Observatory seems to be off the Internet this morning.   It appears this started sometime after midnight local time  (PDT).  Further information will be posted to the Bulletin Board when it is availible. [UPDATE: Hanford is now back on -line]",
        "date" => "September 28, 2007",
        "link" => "/forum_thread.php?id=112",
        "author" => "myers"
    ),

    array("title" => "Cosmic Ray e-Lab server down Saturday ",
        "description" => "The cosmic rays e-Lab server (http://quarknet.fnal.gov/e-lab or http://www.i2u2.org/elab/cosmic) will be offline on Sat, 22 September, 2007, from  0600 to 1800 CDT (1100 to 2300 UTC).   Argonne IT staff plans to reconfigure power distribution for the server cluster.  We apologize for any disruption of e-Lab activities",
        "date" => "September 20, 2007",
        "author" => "rspete"
    ),

    array("title" => "File Uploads in the library",
        "description" => "It is now possible to upload non-image files to the Library (wiki).  Allowed file types are .pdf, .doc, .ppt and .xls.",
        "date" => "September 20, 2007",
        "link" => "/library/index.php/Help:File_Upload",
        "author" => "myers"
    ),

    array("title" => "LIGO Analysis Tool unavailable",
        "description" => "The machine which hosts the LIGO Analysis Tool from Hanford has been turned off due to fires in the area (just as a precaution). 
[UPDATE: tekoa is now back in service.]",
        "date" => "August 17, 2007",
        "author" => "myers",
        "link" => "/forum_thread.php?id=108"
    ),

    array("title" => "Welcome to the Workshop",
        "description" => "Welcome to the participants in the LIGO I2U2 Workshop at Hanford today and tomorrow.",
        "date" => "August 13, 2007",
        "author" => "myers"
    ),

    array("title" => "LIGO data now flowing",
        "description" => "LIGO data are now flowing again.",
        "date" => "March 6, 2007",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=84#293",
        "author" => "myers"
    ),

    array("title" => "No new LIGO data",
        "description" => "Right now we are not getting any new data for the LIGO Analysis Tool.  New data should be available after a server is upgraded at LHO.",
        "date" => "March 1, 2007 21:38 UTC",
        "link" => "/forum_thread.php?id=84",
        "author" => "myers"
    ),

    array("title" => "LHO Network Outage",
        "description" => "The primary network connection at the LIGO Hanford Observatory will be down for maintenance starting at midnight (PST) Feb 8th and lasting from 4 to 6 hours.  The Analysis Tool will likely not be available during that period.",
        "date" => "February 6, 2007 19:31 UTC",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=83",
        "author" => "myers"
    ),

    array("title" => "LIGO Analysis Tool software updated",
        "description" => "The LIGO Analysis Tool software has been updated to version 0.31",
        "date" => "January 18, 2007 23:20 UTC",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=80",
        "author" => "myers"
    ),

    array("title" => "Glossary software updated",
        "description" => "The software used to provide the glossary for this site has been upgraded.",
        "date" => "January 15, 2007 21:05 UTC",
        "author" => "myers",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=78"
    ),

    array("title" => "I2U2 Project Meeting",
        "description" => "I2U2 colleagues from Fermilab, the Adler Planetarium, CMS, LIGO, ATLAS, STAR, and the University of Chicago will meet at Fermilab January 24-25, 2007.",
        "date" => "January 5, 2007 01:45 UTC",
        "author" => "myers"
    ),

    array("title" => "Site mirrored at LHO",
        "description" => "This discussion/news site is now mirrored at the LIGO Hanford Observatory",
        "date" => "October 6, 2006 12:31 UTC",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=69#210",
        "author" => "myers"
    ),

    array("title" => "Welcome to the Workshop",
        "description" => "We welcome the participants in the LIGO I2U2 Workshop at Hanford, today and tomorrow. ",
        "date" => "August 10, 2006 21:13 UTC",
        "author" => "myers",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=61"
    ),

    array("title" => "Attachments and keywords",
        "description" => "The discussion forums now provide for file attachments and keyword classification. ",
        "date" => "August 4, 2006 19:55 UTC",
        "author" => "myers",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=57"
    ),

    array("title" => "Restricted Access",
        "description" => "Access to the discussion rooms is now
restricted to registered users, except for the 'public' areas and the Help Desks.",
        "date" => "February 9, 2006  ",
        "author" => "myers",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=19"
    ),

    array("title" => "Profiles and Pictures",
        "description" => "Welcome to those of you who are just joining
    this site.  You are encouraged to add some background information
    about yourself to your profile page.",
        "date" => "February 3, 2006  ",
        "author" => "myers",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=23"
    ),

    array("title" => "Meeting and Discussion rooms created",
        "description" => "The initial set of meeting and discussion
         rooms has been created.  There are donuts in the Cafe.",
        "date" => "January 20, 2006  ",
        "author" => "myers",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=3"
    ),

    array("title" => "I2U2 wiki created",
        "description" => "A wiki web has been created for I2U2. ",
        "date" => "January 17, 2006  ",
        "author" => "myers",
        "link" => "http://vds.uchicago.edu/twiki/bin/view/I2U2/WebHome"
    ),

    array("title" => "I2U2 Discussion/News site created",
        "description" => "The I2U2 discussion site, based on the BOINC
	forum and RSS news code, has been started.   The discussion
        rooms themselves should be up and running soon. ",
        "date" => "January 16, 2006  ",
        "link" => "http://www13.i2u2.org/forum_thread.php?id=2",
        "author" => "myers"
    ),

    array("title" => "I2U2 all-hands meeting",
        "description" => "The kickoff meeting for I2U2 partners
        was held at Fermilab on December 12-13,
        2005.	Copies of the presentations, as well as the Planning
        and Target notes from the end of the meeting, are available
        from the Fermilab website.",
        "link" => "http://www-ed.fnal.gov/uueo/i2u2.html",
        "date" => "December 12, 2005",
        "author" => "myers"
    ),

);
?>