const dataFiles = [
		' ',
		'Run552_list_no_swap_event.txt',
		'Run552_list_no_swap_converted.txt',
		'Run480_list_no_swap_event.txt',
		'Run480_list_no_swap_converted.txt',
		'Run418_list_no_swap_event.txt',
		'Run418_list_no_swap_converted.txt',
		'Run401_list_no_swap_event.txt',
		'Run401_list_no_swap_converted.txt',
		'Run398_list_no_swap_event.txt',
		'Run398_list_no_swap_converted.txt',
		'Run398_list_no_swap_event_part1.txt',
		'Run398_list_no_swap_event_part2.txt',
		'Run398_list_no_swap_event_part3.txt',
		'Run398_list_no_swap_converted_part1.txt',
		'Run398_list_no_swap_converted_part2.txt',
		'Run398_list_no_swap_converted_part3.txt',
		'Run387_list_no_swap_event.txt',
		'Run387_list_no_swap_converted.txt',
		'Run387_list_no_swap_event_part1.txt',
		'Run387_list_no_swap_event_part2.txt',
		'Run387_list_no_swap_event_part3.txt',
		'Run387_list_no_swap_converted_part1.txt',
		'Run387_list_no_swap_converted_part2.txt',
		'Run387_list_no_swap_converted_part3.txt',
		'Run365_list_no_swap_event.txt',
		'Run365_list_no_swap_converted.txt',
		'Run365_list_no_swap_event_part1.txt',
		'Run365_list_no_swap_event_part2.txt',
		'Run365_list_no_swap_event_part3.txt',
		'Run365_list_no_swap_converted_part1.txt',
		'Run365_list_no_swap_converted_part2.txt',
		'Run365_list_no_swap_converted_part3.txt',
		'Run340_list_no_swap_event.txt',
		'Run340_list_no_swap_converted.txt',
		'Run340_list_no_swap_event_part1.txt',
		'Run340_list_no_swap_event_part2.txt',
		'Run340_list_no_swap_event_part3.txt',
		'Run340_list_no_swap_converted_part1.txt',
		'Run340_list_no_swap_converted_part2.txt',
		'Run340_list_no_swap_converted_part3.txt',
		'Run324_list_no_swap_event_part1.txt',
		'Run324_list_no_swap_event_part2.txt',
		'Run324_list_no_swap_event_part3.txt',
		'Run324_list_no_swap_converted_part1.txt',
		'Run324_list_no_swap_converted_part2.txt',
		'Run324_list_no_swap_converted_part3.txt',
		'Run298_list_no_swap_event_part1.txt',
		'Run298_list_no_swap_event_part2.txt',
		'Run298_list_no_swap_event_part3.txt',
		'Run298_list_no_swap_converted_part1.txt',
		'Run298_list_no_swap_converted_part2.txt',
		'Run298_list_no_swap_converted_part3.txt',
		'Run275_list_no_swap_event_part1.txt',
		'Run275_list_no_swap_event_part2.txt',
		'Run275_list_no_swap_event_part3.txt',
		'Run275_list_no_swap_converted_part1.txt',
		'Run275_list_no_swap_converted_part2.txt',
		'Run275_list_no_swap_converted_part3.txt',
		'Run250_list_no_swap_event_part1.txt',
	    'Run250_list_no_swap_event_part2.txt',
		'Run250_list_no_swap_event_part3.txt',
		'Run250_list_no_swap_converted_part1.txt',
		'Run250_list_no_swap_converted_part2.txt',
		'Run250_list_no_swap_converted_part3.txt',
		'Run228_list_no_swap_event_part1.txt',
		'Run228_list_no_swap_event_part2.txt',
		'Run228_list_no_swap_event_part3.txt',
		'Run228_list_no_swap_converted_part1.txt',
		'Run228_list_no_swap_converted_part2.txt',
		'Run228_list_no_swap_converted_part3.txt',
	    'Run222_list_no_swap_event_part1.txt',
		'Run222_list_no_swap_event_part17.txt',
		'Run222_list_no_swap_converted_part1.txt',
		'Run222_list_no_swap_converted_part17.txt',
		'Run221_list_no_swap_event_part1.txt',
		'Run221_list_no_swap_event_part22.txt',
		'Run221_list_no_swap_converted_part1.txt',
		'Run221_list_no_swap_converted_part22.txt',
		'Run220_list_no_swap_event_part1.txt',
		'Run220_list_no_swap_event_part21.txt',
		'Run220_list_no_swap_converted_part1.txt',
		'Run220_list_no_swap_converted_part21.txt',
		'Run212_list_no_swap_event_part1.txt',
		'Run212_list_no_swap_event_part2.txt',
	    'Run212_list_no_swap_converted_part1.txt',
	    'Run212_list_no_swap_converted_part2.txt',
		'Run203_list_no_swap_event_part1.txt',
		'Run203_list_no_swap_event_part5.txt',
		'Run203_list_no_swap_converted_part1.txt',
		'Run203_list_no_swap_converted_part5.txt',
		'Run193_list_no_swap_event.txt',
		'Run193_list_no_swap_converted.txt',		
	    'Run192_list_no_swap_event_part1.txt',
		'Run192_list_no_swap_event_part8.txt',
		'Run192_list_no_swap_converted_part1.txt',
		'Run192_list_no_swap_converted_part8.txt',
		'Run191_list_no_swap_event.txt',
		'Run191_list_no_swap_converted.txt',
		'Run182_list_no_swap_event.txt',
		'Run182_list_no_swap_converted.txt',
]
// Export functions for ES module consumers and also attach to globalThis for legacy code.
export {
  dataFiles,
 };
// Also expose to global scope for backward compatibility
if (typeof window !== 'undefined') {
  window.dataFiles = dataFiles;
}

// CommonJS fallback for tests or environments using require()
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = {
    dataFiles,
  };
 }