#!/bin/bash

rm -f errors.log

while [ "$1" != "" ]; do
	echo "Processing $1"
	DIR=`basename $1 .root`
	mkdir -p $DIR
	if [ ! -f $1 ]; then
		echo "No such file ($1)"
		exit 1
	fi
	for L in `cat extract.lst`; do
		echo "   extracting $L"
		root -b -q -l Extract.C\(\"$1\",\"$L\"\) 2 >>errors.log |./filter >$DIR/$L
		EC=$?
		if [ "$EC" -ne "0" ]; then
			echo "Root failed ($EC)"
			exit 2
		fi
	done
	shift
done