alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('DAQ: QuarkNet Data Acquisition Board - circuit board with the CPLD, TMC, microcontroller, and input/output ports mounted.  See: <A HREF="javascript:showRefLink(\'flash/DAQII.html\')">Electronic Simulation</A> - shower study data aquisition.','Glossary', 't', 'DAQ');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values (' Greenwich Mean Time (<a href="http://wwp.greenwichmeantime.com" target="_blank">GMT</a>) is the mean solar time at the Royal Greenwich Observatory in Greenwich near London in England, which by convention is at 0 degrees geographic longitude. Noon Greenwich Mean Time is the moment when the Sun crosses the Greenwich meridian (and reaches its highest point in the sky in Greenwich).  On January 1, 1972, GMT was replaced as the international time reference by Coordinated Universal Time (<a href="javascript:glossary(\'UTC\')">UTC</a>), maintained by an ensemble of atomic clocks around the world.','Glossary', 't', 'GMT');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values (' Global Positioning System -- A set of 24 satellites primarily providing navigation information.  Also, the system distributes coordinated time signals derived from atomic clocks managed by the  <A HREF="javascript:showRefLink(\'http://aa.usno.navy.mil/faq/docs/UT.html\',800,650)">USNO</A>.  Tutorial: <A HREF="javascript:showRefLink(\'http://www.trimble.com/gps/\',800,650)">GPS</A>','Glossary', 't', 'GPS');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('Time kept on the Greenwich meridian (longitude zero), five hours ahead of Eastern Standard Time. Times given in UT are almost always given in terms of a 24-hour clock. Thus, 14:42 (often written simply 1442) is 2:42 p.m., and 21:17 (2117) is 9:17 p.m. <a href="http://aa.usno.navy.mil/faq/docs/UT.html"target="_blank">USNO<a>','Glossary', 't', 'UTC');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('Altitude is the vertical elevation distance measured from mean sea level.  Measure altitude by:<br/> a)  Elevation contours from a topographic map: see <A HREF="javascript:showRefLink(\'http://mapserver.maptech.com/homepage/index.cfm\',800,650)">MapServer</a> for online topo maps.<br/> b)  Instrument measurement using a barometer: see <A HREF="javascript:showRefLink(\'http://www.nfinity.com/~exile/howhigh.htm\',800,650)">Barometer</a> for online instructions.<br/> c)  Find an elevation of a nearby landmark: see <A HREF="javascript:showRefLink(\'http://stuff.mit.edu/cgi/geo?location=philadelphia%2C+pa\',800,650)">Elevation</a> for online location selection.<br/> d)  Use a survey quality <a HREF="javascript:glossary(\'GPS\',200)">GPS</a> unit.  Inexpensive hand-held units will approximate altitude to within only <br/>100 ft.','Glossary', 't', 'altitude');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values (' The pressure force caused by the weight of air above the surface of the Earth.  Usually measured by a barometer and given in units of kPa, inches of Hg, or millibars.  See <A HREF="javascript:showRefLink(\'http://www.sengpielaudio.com/calculator-pressure.htm\')">"Convert Barometric Pressure"</a> - to learn more.<br/> ','Glossary', 't', 'barometric_pressure');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('particle from the cosmos studied by scientists','Glossary', 't', 'cosmic_ray');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('Each cosmic ray detector has up to four counters. Here we have two counters, each consisting of a <a HREF="javascript:glossary(\'scintillator\',350)">scintillator </a>and <a HREF="javascript:glossary(\'photomultiplier_tube\',100)">photomultiplier tube </a>connected to the <a HREF="javascript:glossary(\'DAQ\',130)">DAQ </a>board.<br/><IMG SRC="graphics/glossary_detector.gif">','Glossary', 't', 'counter');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('A process in which an original particle (or nucleus) disappears and is replaced by two or more particles (called decay products.) <p> Decays conserve <i>energy</i>, <i>charge</i> and <i>momentum</i>. The summed mass of the decay products is less than the mass of the original. The vector sum of the decay products\' momentum must equal the momentum of the original particle. The summed charge of all decay products must equal the charge of the original.','Glossary', 't', 'decay');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values (' The QuarkNet cosmic ray detector includes <a HREF="javascript:glossary(\'counter\',350)">counters</a>, <a HREF="javascript:glossary(\'DAQ\',130)">DAQ </a>board, power supply, <a HREF="javascript:glossary(\'GPS\',200)">GPS</a> receiver, and cables.  Each cosmic ray detector has up to four counters. Here we have two counters, each consisting of a scintillator and photomultiplier tube connected to the DAQ board.<br/><IMG SRC="graphics/glossary_detector.gif">','Glossary', 't', 'detector');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('<a HREF="javascript:glossary(\'rate\',200)">Rate</a> particles hit. The number of particles per meter<sup>2</sup> per time (60 seconds).','Glossary', 't', 'flux');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('Arrangement of <a HREF="javascript:glossary(\'scintillator\',350)">scintillators</a> - stacked <IMG SRC="http://quarknet.uchicago.edu/elab/cosmic/graphics/stacked.gif"> are good for <a HREF="javascript:glossary(\'lifetime\',200)">lifetime</a> studies; unstacked <IMG SRC="http://quarknet.uchicago.edu/elab/cosmic/graphics/unstacked.gif"> are for <a HREF="javascript:glossary(\'shower\',350)">shower</a> studies.','Glossary', 't', 'geometry');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('A collection of web connected computers for sharing power and storage resources.  <A HREF="javascript:showRefLink(\'http://gridcafe.web.cern.ch/gridcafe/\')">Grid Cafe</a> - learn more about the Grid.<br/>','Glossary', 't', 'grid');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('		A number system with a base of 16. The integers are:  		<p> 		<center> 			<font color="FF0000"> 				<nobr> 					0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F  				</nobr> 			</font> 		</center> 		<p> 			Use the form to convert from one to other bases:  		<form> 			<center> 				<table border="2"> 					<tr> 						<td> 							Decimal:  						<td> 							<input type="text" name="decimal" value="0" size="5" maxlength="5" onchange="decCompute(this.form)"> 					<tr> 						<td> 							Hex:  						<td> 							<input type="text" name="hex" value="0000" size="4" maxlength="4" onchange="hexCompute(this.form)"> 					<tr> 						<td> 							Binary:  						<td> 							<input type="text" name="binary" value="00000000" size="8" maxlength="8" onchange="binCompute(this.form)"> 				</table> 			</center> 		</form> ','Glossary', 't', 'hexadecimal_number');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The mean time for a particle to <a HREF="javascript:glossary(\'decay\',350)">decay</a>. Similar to half-life for radioactive nuclei.','Glossary', 't', 'lifetime');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The QuarkNet detectors require a dark environment. Plastic or glass scintillator is mated using optical glue and shaped fittings to PMTs. The scintillators are covered with reflective material (aluminum foil works) and then with black paper and tape to make them "light-tight." ','Glossary', 't', 'light_leaks');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('A charged, unstable lepton about 200 times more massive than an electron.','Glossary', 't', 'muon');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('Vacuum tube that converts extremely low light levels into electrical signals. Sometimes called a PMT.','Glossary', 't', 'photomultiplier_tube');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The pulse width, called "time over threshold", is the time the signal is over the threshold value.<BR><IMG SRC="graphics/pulse.gif">','Glossary', 't', 'pulse');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The <b>pulse width</b>, also called <b>time over threshold</b>, is the total time the signal is over the threshold value.<BR><IMG SRC="graphics/pulse.gif">','Glossary', 't', 'pulse_width');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The ratio of the number of events during a given length of time: rate = #events / time.  Will yield flux when rate is divided by the area of a detector.','Glossary', 't', 'rate');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The light created by a charged particle moving through scintillating plastic.','Glossary', 't', 'scintillation_light');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('A material that gives off light when a charged  particle passes through it. <p> These are typically made of plastic that has been doped with molecules that gain energy from the passing electric field of charged particles. The energy is stored in electron orbitals and then promptly released in the form of light.<p>  <img src="graphics/scint.jpg" alt="">','Glossary', 't', 'scintillator');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('Primary cosmic rays can interact with nucleons in Earth\'s upper atmosphere.  Showers occur when these primaries are extremley energetic, and produce large numbers of secondary particles (mostly pions and kaons).  The secondaries promptly decay into the particles that strike Earth\'s surface. During a shower, thousands of these particles can strike an area as large as several square kilometers nearly simultaneously. ','Glossary', 't', 'shower');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The Sun provides a constant flux of charged particles.  The level of these particles rise and fall depending on the solar activity.  These events result from solar flares.  When the particles reach the Earth they cause aurora, geomagnetic storms, and disruption of made-made infrastructure such as navigation systems and electrical power grids.  To learn more go to the <A HREF="javascript:showRefLink(\'http://www.sec.noaa.gov/primer/primer.html\',800,750)">Space Weather Primer</a>.  To see current solar conditions go to the <A HREF="javascript:showRefLink(\'http://www.sec.noaa.gov/today.html\',800,650)">Today\'s Space Weather</a>. <br/>','Glossary', 't', 'solar_activity');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('The relativistic effect explained by Einstein\'s Theory that slows the clock of a moving object relative to a  stationary observer.  <A HREF="javascript:showRefLink(\'http://www.glenbrook.k12.il.us/gbssci/phys/shwave/tdilate.html\',800,650)">Time Dilation Tutorial</A>','Glossary', 't', 'time_dilation');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('Time of day normally refers to the clock everyone uses.  This time is referenced to the Sun and called Solar Time.  However, another standard time reference uses the stars instead of the Sun.  This is called Sidereal Time. ','Glossary', 't', 'time_of_day');
alter table drop default;
alter table set default id=MAX(id)+1;
insert into comment (body, discriminator, is_read, title) values ('A time value attached to an event on the DAQ.  The time derives its accuracy from the GPS time signal picked up by the GPS module attached to the DAQ.  The time precision is of the order of tens of nanoseconds, and this precision allows the coordination of data during a cosmic ray shower.','Glossary', 't', 'time_stamp');
alter table drop default;
